### ISSUE TITLE
softmax activation fails

### ISSUE THREAD

**Issue by scott2b** [peterbayerle/huggingface_notebook#1]
The attempted softmax activation in create_predictor fails with the following error:

```
ValueError: Attempt to convert a value (TFSequenceClassifierOutput(loss=None, logits=array([[-0.1524909 ,  0.16800232]], dtype=float32), hidden_states=None, attentions=None)) with an unsupported type (<class 'transformers.modeling_tf_outputs.TFSequenceClassifierOutput'>) to a Tensor.
```

**Comment by scott2b** [comment]
It seems to work to replace the relevant code with the following:

```
preds = model.predict(tfdataset)
preds = activations.softmax(tf.convert_to_tensor(preds[0])).numpy()
return preds[0]
```

**Comment by peterbayerle** [comment]
thanks for catching this .. looks like `predict` now returns a `transformers.modeling_tf_outputs.TFSequenceClassifierOutput` object and not the logits like before. Update made to the notebook! 🤗
